version: "3.7"
services:
  web:
    volumes:
      - ./src:/www
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  php:
    volumes:
      - ./src:/www
    environment:
      PROJECT_URL: http://localhost:8080

secrets:
  db_root_password:
    file: db/secret
  db_password:
    file: db/secret

networks:
  inter-stack:
    internal: true