version: "3.7"
services:
  web:
    ports:
      - 8080:80
  php:
    container_name: ${PROJECT}_php
    environment:
      PROJECT_URL: http://localhost:8080
  db:
    container_name: ${PROJECT}_db

secrets:
  db_root_password:
    file: db/secret
  db_password:
    file: db/secret

networks:
  inter-stack:
    internal: true      