version: "3.7"
services:
  web:
    image: ${REGISTRY_PREFIX}${PROJECT}-web:${VERSION_TAG}
    build:
      context: .
      dockerfile: web/Dockerfile
    volumes:
      - wwwdata:/www
    networks:
      - inter-stack
      - intra
  php:
    image: ${REGISTRY_PREFIX}${PROJECT}-php:${VERSION_TAG}
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - wwwdata:/www      
    environment:
      PROJECT_URL: ${PROJECT_URL}
      DB_HOSTNAME: ${PROJECT}_db
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_NAME}
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_PORT: 3306
    secrets:
      - db_password       
    networks:
      - intra      
  db:
    image: ${REGISTRY_PREFIX}${PROJECT}-db:10${DB_VERSION_TAG}
    build: ./db
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_NAME}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - intra
    secrets:
      - db_root_password
      - db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.persistent == extvol1
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 50M

secrets:
  db_root_password:
    name: ${PROJECT}_db_root_password
    external: true
  db_password:
    name: ${PROJECT}_db_password
    external: true

volumes:
  mysqldata:
  wwwdata:
    
networks:
  inter-stack:
    external: true
  intra: 